alias code="\"/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code\""
alias vim="$(which nvim)"
alias pod="arch -x86_64 pod";
alias ls="exa"
alias pub="flutter pub"
alias pinentry='pinentry-mac'
alias dlf='yt-dlp --cookies-from-browser firefox -S res:1080'
export EDITOR='/opt/homebrew/bin/nvim'
export GPG_TTY=$(tty)
